In [5]:
%pip install pandas matplotlib seaborn plotly statsmodels

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Using cached matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting plotly
  Downloading plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Collecting statsmodels
  Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting scipy!=1.9.2,>=1.8 (from statsmodels)
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading plotly-6.9.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------  9.7/9.9 MB 54.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 48.6 MB/s  0:00:00
Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 9.6/9.6 MB 77.7 MB/s  0:00:00
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 12.6/12.6 MB 88.0 MB/s  0:00:00
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------  7.1/7.2 MB 44.1 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 34.0 MB/s  0:00:00
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ----------------- ---------------------- 16.0/37.3 MB 78.7 MB/s eta 0:00:01
   -------------------------------------- - 36.2/37.3 MB 87.9 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 71.0 MB/s  0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pyparsing, pillow, numpy, narwhals, kiwisolver, fonttools, cycler, scipy, plotly, patsy, pandas, contourpy, statsmodels, matplotlib, seaborn

   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   -- -------------------------------------  1/16 [pyparsing]
   ----- ----------------------------------  2/16 [pillow]
   ----- ----------------------------------  2/16 [pillow]
   ----- ----------------------------------  2/16 [pillow]
   ----- ----------------------------------  2/16 [pillow]
   ----- ----------------------------------  2/16 [pillow]
   ----- ----------------------------------  2/16 [pillow]
   ----- ----------------------------------  2/16 [pillow]
   ----- ----------------------------------  2/16 [pillow]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ------- --------------------------------  3/16 [numpy]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   ---------- -----------------------------  4/16 [narwhals]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   --------------- ------------------------  6/16 [fonttools]
   ----------------- ----------------------  7/16 [cycler]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   -------------------- -------------------  8/16 [scipy]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ---------------------- -----------------  9/16 [plotly]
   ------------------------- -------------- 10/16 [patsy]
   ------------------------- -------------- 10/16 [patsy]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]
   --------------------------- ------------ 11/16 [pandas]

In [7]:
import matplotlib.pyplot as plt
import pandas as pd
import plotly.graph_objects as go
import seaborn as sns
import statsmodels.api as sm

In [ ]:
# Data import & cleaning
r_and_d_expenditure = pd.read_csv('data/API_GB.XPD.RSDV.GD.ZS_DS2_en_csv_v2_232.csv', skiprows=4)
researchers_per_million = pd.read_csv('data/API_SP.POP.SCIE.RD.P6_DS2_en_csv_v2_37695.csv', skiprows=4)
PM_Exposure = pd.read_csv('data/API_SP.POP.SCIE.RD.P6_DS2_en_csv_v2_37695.csv', skiprows=4)

In [11]:
r_and_d_expenditure

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.277537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,"Yemen, Rep.",YEM,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,South Africa,ZAF,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.76257,0.68586,0.613040,0.60296,0.6139,0.61479,NaN,NaN,NaN,NaN
263,Zambia,ZMB,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,Zimbabwe,ZWE,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
researchers_per_million

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,"Yemen, Rep.",YEM,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,South Africa,ZAF,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,516.53674,500.79079,479.86558,459.98774,454.79773,444.16298,NaN,NaN,NaN,NaN
263,Zambia,ZMB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,Zimbabwe,ZWE,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
PM_Exposure

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,"Yemen, Rep.",YEM,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,South Africa,ZAF,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,516.53674,500.79079,479.86558,459.98774,454.79773,444.16298,NaN,NaN,NaN,NaN
263,Zambia,ZMB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,Zimbabwe,ZWE,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
r_and_d_expenditure = r_and_d_expenditure.drop(columns=[c for c in r_and_d_expenditure.columns if "Unnamed" in c])
years = [c for c in r_and_d_expenditure.columns if c[:4].isdigit()]
r_and_d_expenditure = r_and_d_expenditure.melt(id_vars=["Country Name", "Country Code"],          # = Unpivot Other Columns
                                   value_vars=years, var_name="Year", value_name="R&D Expenditure")
r_and_d_expenditure = r_and_d_expenditure.dropna(subset=["R&D Expenditure"])
r_and_d_expenditure["Year"] = r_and_d_expenditure["Year"].astype(int)
r_and_d_expenditure

       Country Name Country Code  Year  R&D Expenditure
9549      Argentina          ARG  1996          0.41749
9553      Australia          AUS  1996          1.66218
9554        Austria          AUT  1996          1.58947
9555     Azerbaijan          AZE  1996          0.23533
9557        Belgium          BEL  1996          1.74299
...             ...          ...   ...              ...
17164  Saudi Arabia          SAU  2024          0.63522
17173        Serbia          SRB  2024          0.93978
17191          Togo          TGO  2024          0.22229
17207       Ukraine          UKR  2024          0.36988
17211    Uzbekistan          UZB  2024          0.10416

[3198 rows x 4 columns]

In [17]:
researchers_per_million = researchers_per_million.drop(columns=[c for c in researchers_per_million.columns if "Unnamed" in c])
years = [c for c in researchers_per_million.columns if c[:4].isdigit()]
researchers_per_million = researchers_per_million.melt(id_vars=["Country Name", "Country Code"],          # = Unpivot Other Columns
                                   value_vars=years, var_name="Year", value_name="Researchers per Million")
researchers_per_million = researchers_per_million.dropna(subset=["Researchers per Million"])
researchers_per_million["Year"] = researchers_per_million["Year"].astype(int)
researchers_per_million

,Country Name,Country Code,Year,Researchers per Million
9553,Australia,AUS,1996,3353.705300
9557,Belgium,BEL,1996,2477.439060
9561,Bulgaria,BGR,1996,1771.854220
9575,Canada,CAN,1996,3055.672470
9576,Central Europe and the Baltics,CEB,1996,1410.613645
...,...,...,...,...
17173,Serbia,SRB,2024,2687.547080
17191,Togo,TGO,2024,57.794020
17202,Tunisia,TUN,2024,1667.611640
17209,Uruguay,URY,2024,937.570390
17211,Uzbekistan,UZB,2024,639.536510

In [18]:
PM_Exposure = PM_Exposure.drop(columns=[c for c in PM_Exposure.columns if "Unnamed" in c])
years = [c for c in PM_Exposure.columns if c[:4].isdigit()]
PM_Exposure = PM_Exposure.melt(id_vars=["Country Name", "Country Code"],          # = Unpivot Other Columns
                               value_vars=years, var_name="Year", value_name="PM Exposure")
PM_Exposure = PM_Exposure.dropna(subset=["PM Exposure"])
PM_Exposure["Year"] = PM_Exposure["Year"].astype(int)
PM_Exposure

                         Country Name Country Code  Year  PM Exposure
9553                        Australia          AUS  1996  3353.705300
9557                          Belgium          BEL  1996  2477.439060
9561                         Bulgaria          BGR  1996  1771.854220
9575                           Canada          CAN  1996  3055.672470
9576   Central Europe and the Baltics          CEB  1996  1410.613645
...                               ...          ...   ...          ...
17173                          Serbia          SRB  2024  2687.547080
17191                            Togo          TGO  2024    57.794020
17202                         Tunisia          TUN  2024  1667.611640
17209                         Uruguay          URY  2024   937.570390
17211                      Uzbekistan          UZB  2024   639.536510

[2475 rows x 4 columns]